export const Constants = {
    SIGNIN_REQUEST: 'SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    SIGNOUT: 'SIGNOUT',
    ADD_UNPUBLISH: 'ADD_UNPUBLISH',
    REMOVE_ONE_UNPUBLISH: 'REMOVE_ONE_UNPUBLISH',
    CLEAR_UNPUBLISH: 'CLEAR_UNPUBLISH',
    ADD_UNPUBLISH_REQ: 'ADD_UNPUBLISH_REQ',
    ADD_UNPUBLISH_SUCCESS: 'ADD_UNPUBLISH_SUCCESS',
    ADD_UNPUBLISH_ERROR: 'ADD_UNPUBLISH_ERROR',
}